/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../app/services/types.generated';

import { api } from '../../app/services/baseApi';
export type CreateTodoMutationVariables = Types.Exact<{
  description?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;


export type CreateTodoMutation = { __typename?: 'Mutation', createTodo?: { __typename?: 'CreateTodoPayload', todo?: { __typename?: 'Todo', description: string, id: number } } };


export const CreateTodoDocument = `
    mutation createTodo($description: String = "") {
  createTodo(input: {todo: {description: $description}}) {
    todo {
      description
      id
    }
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    createTodo: build.mutation<CreateTodoMutation, CreateTodoMutationVariables | void>({
      query: (variables) => ({ document: CreateTodoDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useCreateTodoMutation } = injectedRtkApi;

