/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../app/services/types.generated';

import { api } from '../../app/services/baseApi';
export type DeleteTodoByIdMutationVariables = Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;


export type DeleteTodoByIdMutation = { __typename?: 'Mutation', deleteTodoById?: { __typename?: 'DeleteTodoPayload', todo?: { __typename?: 'Todo', description: string, id: number } } };


export const DeleteTodoByIdDocument = `
    mutation deleteTodoById($id: Int = 10) {
  deleteTodoById(input: {id: $id}) {
    todo {
      description
      id
    }
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    deleteTodoById: build.mutation<DeleteTodoByIdMutation, DeleteTodoByIdMutationVariables | void>({
      query: (variables) => ({ document: DeleteTodoByIdDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useDeleteTodoByIdMutation } = injectedRtkApi;

